--- 
blank_issues_enabled: true
contact_links:
  -
    name: "Documentation"
    about: "Here you can read Teng's documentation"
    url: "https://github.com/Sv443/Teng/blob/master/docs/home.md#readme"
  -
    name: "Chat"
    about: "If you want, you can join my Discord server"
    url: "https://sv443.net/discord"
